"""empty message

Revision ID: 283bbd54ae3b
Revises: d2fea35f6d92
Create Date: 2022-12-29 10:06:40.788805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '283bbd54ae3b'
down_revision = 'd2fea35f6d92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(length=150), nullable=True),
    sa.Column('last_name', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('g_auth_verify', sa.Boolean(), nullable=True),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('word',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('savedword', sa.String(length=150), nullable=False),
    sa.Column('meaning', sa.String(length=300), nullable=True),
    sa.Column('speechtype', sa.String(length=150), nullable=True),
    sa.Column('user_token', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_token'], ['user.token'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('word')
    op.drop_table('user')
    # ### end Alembic commands ###
